# Fly.io deployment configuration
app = "ml-models-energy"  # Match the app name from your error logs
primary_region = "iad"

[build]
  builder = "dockerfile"

[deploy]
  strategy = "rolling"
  wait_timeout = "10m"  # Increased timeout for ML model loading
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  # Add health check with longer grace period
  [http_service.checks]
    grace_period = "60s"  # Give more time for ML models to load
    interval = "30s"
    timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 2  # Increased from 1 for better performance
  memory_mb = 1024  # Increased from 512 for ML models

[env]
  PORT = "8000"
  PYTHON_VERSION = "3.9"
